apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGxxbXR5N2t1
  CLOUDINARY_KEY: NzUyMTk2NDU2ODQ4NTQz
  CLOUDINARY_SECRET: NmpvbUhTS1BWUDZmTXE0UnhoOExvd19SX2Rv
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMmhoYUdsa2MzbGxaQ0lzSW1FaU9pSmpiWEF3ZFRCamNqUXhNWHB0TW5Cek9EVnhZWFpxZHpkcEluMC5FSTJRWnhDckZZYnVKdGhlZDNwTXN3
  DB_URL: bW9uZ29kYitzcnY6Ly9zaGFoaWQ6YWRtaW4xMTIyQGNsdXN0ZXIwLnZjc200Y2subW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
